name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.24.5'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build k6 with extension
        run: xk6 build --with github.com/zilliz/xk6-milvus=.

      - name: Verify build
        run: ./k6 version

      - name: Upload k6 binary
        uses: actions/upload-artifact@v4
        with:
          name: k6-binary
          path: ./k6

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: build
    services:
      milvus:
        image: milvusdb/milvus:latest
        ports:
          - 19530:19530
        options: --health-cmd "curl -f http://localhost:9091/healthz" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download k6 binary
        uses: actions/download-artifact@v4
        with:
          name: k6-binary

      - name: Make k6 executable
        run: chmod +x ./k6

      - name: Wait for Milvus
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:19530/v1/health 2>/dev/null; then
              echo "Milvus is ready"
              break
            fi
            echo "Waiting for Milvus... ($i/30)"
            sleep 2
          done

      - name: Run basic example
        run: ./k6 run examples/basic/test-milvus.js
        env:
          MILVUS_HOST: localhost:19530

      - name: Run advanced example
        run: ./k6 run examples/advanced/flexible-test.js
        env:
          MILVUS_HOST: localhost:19530